In [2]:
import pandas as pd
import numpy as np
import scipy.stats as st

In [3]:
data = pd.read_excel(r'C:\Users\Acer\OneDrive\Desktop\Labs\Customer Information (Responses).xlsx')

In [4]:
data.drop(columns='Timestamp', inplace=True)
data.drop(columns='Annual income(optional)', inplace=True)

In [5]:
data.drop(columns='If no, what bank would you recommend?', inplace=True)

In [6]:
Age_group = pd.cut(data['Age'], bins= 3, labels=['Young', 'Middle-aged', 'Old'])
data['Age_group'] = Age_group

In [7]:
Areas_of_Improvement = data['Where do you feel the bank needs improvement? (Select all that apply)'].str.split(',', 1, expand=True)
Areas_of_Improvement

,0,1
0,Customer service,Easy credit/loans
1,Product range offered,None
2,Customer service,None
3,Customer service,Net banking
4,Product range offered,None
5,NaN,NaN
6,Easy credit/loans,None
7,Product range offered,Proper information about products
8,Customer service,None
9,Customer service,None
10,Product range offered,None
11,Proper information about products,None
12,Easy credit/loans,None
13,Net banking,None
14,Product range offered,Proper information about products
15,Easy credit/loans,None
16,Product range offered,None
17,Nothing,None
18,Proper information about products,None
19,Customer service,"Product range offered, Proper information abo..."
20,Customer service,None
21,Product range offered,None
22,Proper information about products,None
23,Product range offered,None
24,Customer service,"Proper information about products, Net banking"
25,Net banking,None
26,None,None
27,NaN,NaN
28,Net banking,None
29,NaN,NaN
30,Proper information about products,None
31,Net banking,None
32,Easy credit/loans,None
33,Customer service,Proper information about products
34,Customer service,Product range offered
35,Customer service,None
36,Customer service,None
37,Proper information about products,None
38,Easy credit/loans,None
39,Customer service,None
40,Customer service,None

In [8]:
Areas_of_Improvement.drop(columns=1, inplace=True)

In [9]:
data['Areas_of_Improvement'] = Areas_of_Improvement

In [10]:
Bank_selection = data['What do you look for in a bank? (Select all that apply)'].str.split(',', 1, expand=True)
Bank_selection

                      0                                                  1
0     Multiple branches      Customer service, Proximity, Products offered
1      Customer service                                   Products offered
2             Proximity                                               None
3     Multiple branches      Customer service, Proximity, Products offered
4      Customer service                                          Proximity
5      Customer service                                   Products offered
6      Customer service                        Proximity, Products offered
7      Products offered                                               None
8     Multiple branches                                               None
9      Customer service                        Proximity, Products offered
10     Customer service                                               None
11     Customer service                        Proximity, Products offered
12    Multiple branches                        Customer service, Proximity
13     Customer service                       All that I need into the app
14     Customer service   Low prices of basic services + international ...
15     Customer service                                               None
16    Multiple branches                 Customer service, Products offered
17     Customer service                                          Proximity
18     Products offered                                               None
19     Customer service                                               None
20     Customer service                                   Products offered
21     Customer service                                               None
22     Customer service                                               None
23    Multiple branches                                   Products offered
24            Proximity                                               None
25     Customer service                                   Products offered
26     Customer service                                               None
27                  NaN                                                NaN
28     Customer service                                   Deposit Security
29                  NaN                                                NaN
30     Customer service                                               None
31     Customer service                                          Proximity
32    Multiple branches                                   Customer service
33     Customer service                                   Products offered
34     Customer service                        Proximity, Products offered
35     Customer service                                               None
36     Customer service                                               None
37     Customer service                                               None
38  No maintenance fees                                               None
39    Multiple branches                                               None
40     Customer service                                               None

In [11]:
Bank_selection.drop(columns=1, inplace=True)

In [12]:
data['Bank Selection'] = Bank_selection

In [13]:
data["Which branch service channel do you use the most?"].value_counts()

Mobile banking app    27
Online banking         6
Bank ATM               4
Branch banking         2
Name: Which branch service channel do you use the most?, dtype: int64

In [14]:
data.isnull().sum()

Age                                                                                  0
Highest educational Level                                                            0
Marital status                                                                       0
Location                                                                             0
Occupation                                                                           0
Do you have a bank account?                                                          0
Name of your bank                                                                    2
Which branch service channel do you use the most?                                    2
Preferred contact with your bank                                                     2
What do you look for in a bank? (Select all that apply)                              2
How long on average did it take the support team to respond to you ? (in minutes)    2
What do you feel about the overall service quality of your bank?                     2
Was the support useful?                                                              2
Would you recommend your bank to families and friends                                2
How likely are you to continue using your current bank?                              2
Where do you feel the bank needs improvement? (Select all that apply)                3
Age_group                                                                            0
Areas_of_Improvement                                                                 3
Bank Selection                                                                       2
dtype: int64

In [15]:
data.head()

,Age,Highest educational Level,Marital status,Location,Occupation,Do you have a bank account?,Name of your bank,Which branch service channel do you use the most?,Preferred contact with your bank,What do you look for in a bank? (Select all that apply),How long on average did it take the support team to respond to you ? (in minutes),What do you feel about the overall service quality of your bank?,Was the support useful?,Would you recommend your bank to families and friends,How likely are you to continue using your current bank?,Where do you feel the bank needs improvement? (Select all that apply),Age_group,Areas_of_Improvement,Bank Selection
0,19,Bachelors,Single,Europe,Student,Yes,Millennium BCP,Mobile banking app,Telephone,"Multiple branches, Customer service, Proximity...",15.0,4.0,5.0,Yes,5.0,"Customer service, Easy credit/loans",Young,Customer service,Multiple branches
1,22,Bachelors,Single,Europe,Services,Yes,Swedbank,Mobile banking app,Telephone,"Customer service, Products offered",5.0,5.0,5.0,Yes,5.0,Product range offered,Young,Product range offered,Customer service
2,22,Bachelors,Single,Europe,Self-employed,Yes,Millenium BCP,Online banking,In person (at the branch),Proximity,20.0,4.0,4.0,Yes,4.0,Customer service,Young,Customer service,Proximity
3,25,Masters,Single,Europe,Services,Yes,Crédito Agrícola,Mobile banking app,Telephone,"Multiple branches, Customer service, Proximity...",7.0,4.0,5.0,Yes,5.0,"Customer service, Net banking",Young,Customer service,Multiple branches
4,21,Bachelors,Single,Africa,Services,Yes,GTB,Mobile banking app,Telephone,"Customer service, Proximity",5.0,3.0,4.0,Yes,4.0,Product range offered,Young,Product range offered,Customer service

In [16]:
x = data['How long on average did it take the support team to respond to you ? (in minutes)'].fillna(0)

x.astype(int)

0       15
1        5
2       20
3        7
4        5
5        5
6        5
7       10
8        5
9        2
10       5
11       5
12      10
13      60
14    1440
15       5
16    1440
17       0
18       1
19      60
20      30
21      10
22      10
23      25
24      25
25      15
26       5
27       0
28       5
29       0
30      15
31      20
32      16
33      30
34    1440
35      10
36      30
37       2
38       2
39       5
40      10
Name: How long on average did it take the support team to respond to you ? (in minutes), dtype: int32

In [17]:
data['How long on average did it take the support team to respond to you ? (in minutes)']

0     1.500000e+01
1     5.000000e+00
2     2.000000e+01
3     7.000000e+00
4     5.000000e+00
5     5.000000e+00
6     5.000000e+00
7     1.000000e+01
8     5.000000e+00
9     2.000000e+00
10    5.000000e+00
11    5.000000e+00
12    1.000000e+01
13    6.000000e+01
14    1.440000e+03
15    5.000000e+00
16    1.440000e+03
17    1.000000e-11
18    1.000000e+00
19    6.000000e+01
20    3.000000e+01
21    1.000000e+01
22    1.000000e+01
23    2.500000e+01
24    2.500000e+01
25    1.500000e+01
26    5.000000e+00
27             NaN
28    5.000000e+00
29             NaN
30    1.500000e+01
31    2.000000e+01
32    1.600000e+01
33    3.000000e+01
34    1.440000e+03
35    1.000000e+01
36    3.000000e+01
37    2.000000e+00
38    2.000000e+00
39    5.000000e+00
40    1.000000e+01
Name: How long on average did it take the support team to respond to you ? (in minutes), dtype: float64

In [18]:
data.isnull().sum()

Age                                                                                  0
Highest educational Level                                                            0
Marital status                                                                       0
Location                                                                             0
Occupation                                                                           0
Do you have a bank account?                                                          0
Name of your bank                                                                    2
Which branch service channel do you use the most?                                    2
Preferred contact with your bank                                                     2
What do you look for in a bank? (Select all that apply)                              2
How long on average did it take the support team to respond to you ? (in minutes)    2
What do you feel about the overall service quality of your bank?                     2
Was the support useful?                                                              2
Would you recommend your bank to families and friends                                2
How likely are you to continue using your current bank?                              2
Where do you feel the bank needs improvement? (Select all that apply)                3
Age_group                                                                            0
Areas_of_Improvement                                                                 3
Bank Selection                                                                       2
dtype: int64

In [19]:
data_null = data.isnull().sum()
data_null[data_null == 2]

data[data['Areas_of_Improvement'].isnull()]

,Age,Highest educational Level,Marital status,Location,Occupation,Do you have a bank account?,Name of your bank,Which branch service channel do you use the most?,Preferred contact with your bank,What do you look for in a bank? (Select all that apply),How long on average did it take the support team to respond to you ? (in minutes),What do you feel about the overall service quality of your bank?,Was the support useful?,Would you recommend your bank to families and friends,How likely are you to continue using your current bank?,Where do you feel the bank needs improvement? (Select all that apply),Age_group,Areas_of_Improvement,Bank Selection
5,38,PHD,Married,Europe,Manager,Yes,Millennium bcp,Mobile banking app,Telephone,"Customer service, Products offered",5.0,5.0,5.0,Yes,5.0,NaN,Old,NaN,Customer service
27,38,Masters,Married,Europe,Unemployed,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Old,NaN,NaN
29,20,Bachelors,Single,Asia,Student,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Young,NaN,NaN

In [20]:
## df.drop(df.index[2])

In [21]:
data.iloc[[27]]

,Age,Highest educational Level,Marital status,Location,Occupation,Do you have a bank account?,Name of your bank,Which branch service channel do you use the most?,Preferred contact with your bank,What do you look for in a bank? (Select all that apply),How long on average did it take the support team to respond to you ? (in minutes),What do you feel about the overall service quality of your bank?,Was the support useful?,Would you recommend your bank to families and friends,How likely are you to continue using your current bank?,Where do you feel the bank needs improvement? (Select all that apply),Age_group,Areas_of_Improvement,Bank Selection
27,38,Masters,Married,Europe,Unemployed,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Old,NaN,NaN

In [22]:
data = data.drop(27)

In [23]:
data = data.drop(29)

In [24]:
## data[data['Areas_of_Improvement'].isnull()]

In [25]:
def improve(x):
    if type(x) == float:
        return 'no areas of improvement'
    else:
        return x

data['Areas_of_Improvement'].apply(improve)

0                      Customer service
1                 Product range offered
2                      Customer service
3                      Customer service
4                 Product range offered
5               no areas of improvement
6                     Easy credit/loans
7                 Product range offered
8                      Customer service
9                      Customer service
10                Product range offered
11    Proper information about products
12                    Easy credit/loans
13                          Net banking
14                Product range offered
15                    Easy credit/loans
16                Product range offered
17                              Nothing
18    Proper information about products
19                     Customer service
20                     Customer service
21                Product range offered
22    Proper information about products
23                Product range offered
24                     Customer service
25                          Net banking
26                                 None
28                          Net banking
30    Proper information about products
31                          Net banking
32                    Easy credit/loans
33                     Customer service
34                     Customer service
35                     Customer service
36                     Customer service
37    Proper information about products
38                    Easy credit/loans
39                     Customer service
40                     Customer service
Name: Areas_of_Improvement, dtype: object

In [26]:
data.groupby('Age_group').agg({'Areas_of_Improvement':'count'})

             Areas_of_Improvement
Age_group
Young                          20
Middle-aged                    15
Old                             3

In [27]:
data['Areas_of_Improvement']

0                      Customer service
1                 Product range offered
2                      Customer service
3                      Customer service
4                 Product range offered
5                                   NaN
6                     Easy credit/loans
7                 Product range offered
8                      Customer service
9                      Customer service
10                Product range offered
11    Proper information about products
12                    Easy credit/loans
13                          Net banking
14                Product range offered
15                    Easy credit/loans
16                Product range offered
17                              Nothing
18    Proper information about products
19                     Customer service
20                     Customer service
21                Product range offered
22    Proper information about products
23                Product range offered
24                     Customer service
25                          Net banking
26                                 None
28                          Net banking
30    Proper information about products
31                          Net banking
32                    Easy credit/loans
33                     Customer service
34                     Customer service
35                     Customer service
36                     Customer service
37    Proper information about products
38                    Easy credit/loans
39                     Customer service
40                     Customer service
Name: Areas_of_Improvement, dtype: object

In [28]:
data_crosstab = pd.crosstab(data['Age_group'], data['Areas_of_Improvement'], margins = False)
print(data_crosstab)

Areas_of_Improvement  Customer service  Easy credit/loans  Net banking  None  \
Age_group
Young                               11                  3            0     0
Middle-aged                          3                  2            3     1
Old                                  0                  0            1     0

Areas_of_Improvement  Nothing  Product range offered  \
Age_group
Young                       0                      4
Middle-aged                 1                      3
Old                         0                      1

Areas_of_Improvement  Proper information about products
Age_group
Young                                                 2
Middle-aged                                           2
Old                                                   1

In [29]:
### made my survey baised and saw that younger people are easily influenced by the first header that they seee......

## framing bias

In [30]:
# Contingency tables and independence of effects

## H0: age group independent of the areas of imporovement ---
## H1: others were not easily influenced by the header of the survey

#we just need the observed values 
## cars_table=[[256,74],[41,42],[66,34]]

# significance level 
alpha = 0.05

st.chi2_contingency(np.array(data_crosstab))
#statistic, p-value, degrees of freedom, expected probs if H0 holds

(13.743333333333334,
 0.31739801591213046,
 12,
 array([[7.36842105, 2.63157895, 2.10526316, 0.52631579, 0.52631579,
         4.21052632, 2.63157895],
        [5.52631579, 1.97368421, 1.57894737, 0.39473684, 0.39473684,
         3.15789474, 1.97368421],
        [1.10526316, 0.39473684, 0.31578947, 0.07894737, 0.07894737,
         0.63157895, 0.39473684]]))

In [31]:
0.31739801591213046 < alpha

False

In [32]:
data.columns

Index(['Age', 'Highest educational Level', 'Marital status', 'Location',
       'Occupation', 'Do you have a bank account?', 'Name of your bank',
       'Which branch service channel do you use the most?',
       'Preferred contact with your bank',
       'What do you look for in a bank? (Select all that apply)',
       'How long on average did it take the support team to respond to you ? (in minutes)',
       'What do you feel about the overall service quality of your bank?',
       'Was the support useful?',
       'Would you recommend your bank to families and friends',
       'How likely are you to continue using your current bank?',
       'Where do you feel the bank needs improvement? (Select all that apply)',
       'Age_group', 'Areas_of_Improvement', 'Bank Selection'],
      dtype='object')

In [33]:
data.rename(columns = {'Highest educational Level':'Education', 'Would you recommend your bank to families and friends':'Likelihood to recommend', 'Name of your bank':'Bank Name', 'Which branch service channel do you use the most?':'Preferred Service Channel', 'How long on average did it take the support team to respond to you ? (in minutes)':'Customer service response time', 'How likely are you to continue using your current bank?':'Likelihood to continue', 'What do you feel about the overall service quality of your bank?':'Service Quality', 'Preferred contact with your bank':'Preferred contact'}, inplace = True)

In [34]:
data.head()

,Age,Education,Marital status,Location,Occupation,Do you have a bank account?,Bank Name,Preferred Service Channel,Preferred contact,What do you look for in a bank? (Select all that apply),Customer service response time,Service Quality,Was the support useful?,Likelihood to recommend,Likelihood to continue,Where do you feel the bank needs improvement? (Select all that apply),Age_group,Areas_of_Improvement,Bank Selection
0,19,Bachelors,Single,Europe,Student,Yes,Millennium BCP,Mobile banking app,Telephone,"Multiple branches, Customer service, Proximity...",15.0,4.0,5.0,Yes,5.0,"Customer service, Easy credit/loans",Young,Customer service,Multiple branches
1,22,Bachelors,Single,Europe,Services,Yes,Swedbank,Mobile banking app,Telephone,"Customer service, Products offered",5.0,5.0,5.0,Yes,5.0,Product range offered,Young,Product range offered,Customer service
2,22,Bachelors,Single,Europe,Self-employed,Yes,Millenium BCP,Online banking,In person (at the branch),Proximity,20.0,4.0,4.0,Yes,4.0,Customer service,Young,Customer service,Proximity
3,25,Masters,Single,Europe,Services,Yes,Crédito Agrícola,Mobile banking app,Telephone,"Multiple branches, Customer service, Proximity...",7.0,4.0,5.0,Yes,5.0,"Customer service, Net banking",Young,Customer service,Multiple branches
4,21,Bachelors,Single,Africa,Services,Yes,GTB,Mobile banking app,Telephone,"Customer service, Proximity",5.0,3.0,4.0,Yes,4.0,Product range offered,Young,Product range offered,Customer service

In [35]:
data.isnull().sum()

Age                                                                      0
Education                                                                0
Marital status                                                           0
Location                                                                 0
Occupation                                                               0
Do you have a bank account?                                              0
Bank Name                                                                0
Preferred Service Channel                                                0
Preferred contact                                                        0
What do you look for in a bank? (Select all that apply)                  0
Customer service response time                                           0
Service Quality                                                          0
Was the support useful?                                                  0
Likelihood to recommend                                                  0
Likelihood to continue                                                   0
Where do you feel the bank needs improvement? (Select all that apply)    1
Age_group                                                                0
Areas_of_Improvement                                                     1
Bank Selection                                                           0
dtype: int64

In [36]:
X = data[['Age_group']]
y = data['Areas_of_Improvement']

In [37]:
data.isnull().sum()

Age                                                                      0
Education                                                                0
Marital status                                                           0
Location                                                                 0
Occupation                                                               0
Do you have a bank account?                                              0
Bank Name                                                                0
Preferred Service Channel                                                0
Preferred contact                                                        0
What do you look for in a bank? (Select all that apply)                  0
Customer service response time                                           0
Service Quality                                                          0
Was the support useful?                                                  0
Likelihood to recommend                                                  0
Likelihood to continue                                                   0
Where do you feel the bank needs improvement? (Select all that apply)    1
Age_group                                                                0
Areas_of_Improvement                                                     1
Bank Selection                                                           0
dtype: int64

In [38]:
data.to_csv('data.csv', index=False)

KF = KFold(n_splits=3,shuffle=True)
for train_index, test_index in KF.split(X):
    x_train, x_test = X.iloc[list(train_index)], X.iloc[list(test_index)]
    y_train, y_test = y.iloc[list(train_index)], y.iloc[list(test_index)]

In [39]:
## might have to standardize it became my variables are using different scales
## can normalizatoin, work?

In [40]:
## cannot perform minmax scaler on an object

In [41]:
## age and bank selectiont predict the area of improvement

In [42]:
data.drop(columns='Do you have a bank account?', inplace=True)

In [43]:
data.drop(columns='Where do you feel the bank needs improvement? (Select all that apply)', inplace=True)

In [44]:
data.drop(columns='What do you look for in a bank? (Select all that apply)', inplace=True)

In [45]:
data.drop(columns='Was the support useful?', inplace=True)

In [46]:
data.head()

,Age,Education,Marital status,Location,Occupation,Bank Name,Preferred Service Channel,Preferred contact,Customer service response time,Service Quality,Likelihood to recommend,Likelihood to continue,Age_group,Areas_of_Improvement,Bank Selection
0,19,Bachelors,Single,Europe,Student,Millennium BCP,Mobile banking app,Telephone,15.0,4.0,Yes,5.0,Young,Customer service,Multiple branches
1,22,Bachelors,Single,Europe,Services,Swedbank,Mobile banking app,Telephone,5.0,5.0,Yes,5.0,Young,Product range offered,Customer service
2,22,Bachelors,Single,Europe,Self-employed,Millenium BCP,Online banking,In person (at the branch),20.0,4.0,Yes,4.0,Young,Customer service,Proximity
3,25,Masters,Single,Europe,Services,Crédito Agrícola,Mobile banking app,Telephone,7.0,4.0,Yes,5.0,Young,Customer service,Multiple branches
4,21,Bachelors,Single,Africa,Services,GTB,Mobile banking app,Telephone,5.0,3.0,Yes,4.0,Young,Product range offered,Customer service

In [47]:
data.dtypes

Age                                  int64
Education                           object
Marital status                      object
Location                            object
Occupation                          object
Bank Name                           object
Preferred Service Channel           object
Preferred contact                   object
Customer service response time     float64
Service Quality                    float64
Likelihood to recommend             object
Likelihood to continue             float64
Age_group                         category
Areas_of_Improvement                object
Bank Selection                      object
dtype: object

In [48]:
data.isnull().sum()

Age                               0
Education                         0
Marital status                    0
Location                          0
Occupation                        0
Bank Name                         0
Preferred Service Channel         0
Preferred contact                 0
Customer service response time    0
Service Quality                   0
Likelihood to recommend           0
Likelihood to continue            0
Age_group                         0
Areas_of_Improvement              1
Bank Selection                    0
dtype: int64

In [49]:
data['Customer service response time'] = data['Customer service response time'].astype('int')

In [50]:
data.dtypes

Age                                  int64
Education                           object
Marital status                      object
Location                            object
Occupation                          object
Bank Name                           object
Preferred Service Channel           object
Preferred contact                   object
Customer service response time       int32
Service Quality                    float64
Likelihood to recommend             object
Likelihood to continue             float64
Age_group                         category
Areas_of_Improvement                object
Bank Selection                      object
dtype: object

In [51]:
data.head()

,Age,Education,Marital status,Location,Occupation,Bank Name,Preferred Service Channel,Preferred contact,Customer service response time,Service Quality,Likelihood to recommend,Likelihood to continue,Age_group,Areas_of_Improvement,Bank Selection
0,19,Bachelors,Single,Europe,Student,Millennium BCP,Mobile banking app,Telephone,15,4.0,Yes,5.0,Young,Customer service,Multiple branches
1,22,Bachelors,Single,Europe,Services,Swedbank,Mobile banking app,Telephone,5,5.0,Yes,5.0,Young,Product range offered,Customer service
2,22,Bachelors,Single,Europe,Self-employed,Millenium BCP,Online banking,In person (at the branch),20,4.0,Yes,4.0,Young,Customer service,Proximity
3,25,Masters,Single,Europe,Services,Crédito Agrícola,Mobile banking app,Telephone,7,4.0,Yes,5.0,Young,Customer service,Multiple branches
4,21,Bachelors,Single,Africa,Services,GTB,Mobile banking app,Telephone,5,3.0,Yes,4.0,Young,Product range offered,Customer service

In [52]:
data['Service Quality'] = data['Service Quality'].astype('int')
data['Likelihood to continue'] = data['Likelihood to continue'].astype('int')

In [53]:
data.head()

,Age,Education,Marital status,Location,Occupation,Bank Name,Preferred Service Channel,Preferred contact,Customer service response time,Service Quality,Likelihood to recommend,Likelihood to continue,Age_group,Areas_of_Improvement,Bank Selection
0,19,Bachelors,Single,Europe,Student,Millennium BCP,Mobile banking app,Telephone,15,4,Yes,5,Young,Customer service,Multiple branches
1,22,Bachelors,Single,Europe,Services,Swedbank,Mobile banking app,Telephone,5,5,Yes,5,Young,Product range offered,Customer service
2,22,Bachelors,Single,Europe,Self-employed,Millenium BCP,Online banking,In person (at the branch),20,4,Yes,4,Young,Customer service,Proximity
3,25,Masters,Single,Europe,Services,Crédito Agrícola,Mobile banking app,Telephone,7,4,Yes,5,Young,Customer service,Multiple branches
4,21,Bachelors,Single,Africa,Services,GTB,Mobile banking app,Telephone,5,3,Yes,4,Young,Product range offered,Customer service

In [54]:
data.to_csv('finaldata.csv', index=False)

In [55]:
a = data['Areas_of_Improvement'].unique()
a

array(['Customer service', 'Product range offered', nan,
       'Easy credit/loans', 'Proper information about products',
       'Net banking', 'Nothing', 'None'], dtype=object)

In [ ]:
def improve(x):
    if type(x) == float:
        return 'no areas of improvement'
    else:
        return x

data['Areas_of_Improvement'].apply(improve)